apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: microservices-app

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: usersdb
