apiVersion: v1
kind: Secret

metadata:
  name: user-service-secret
  namespace: microservices-app

type: Opaque

stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  JWT_SECRET: dev-secret-change-me
